AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Product Application
  '
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        PRODUCT_TABLE:
          Ref: ProductTable
Resources:
  ProductTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: products
      PrimaryKey:
        Name: id
        Type: String
  ProductApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, DELETE'''
  ProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action:
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:UpdateItem
                - logs:CreateLogStream
                - logs:CreateLogGroup
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/products
            - Sid: VisualEditor1
              Effect: Allow
              Action:
                - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*
      Events:
        AddProduct:
          Type: Api
          Properties:
            Path: /product
            Method: post
            RestApiId:
              Ref: ProductApi
        DeleteProduct:
          Type: Api
          Properties:
            Path: /product/{id}
            Method: delete
            RestApiId:
              Ref: ProductApi
        GetProduct:
          Type: Api
          Properties:
            Path: /product/{id}
            Method: get
            RestApiId:
              Ref: ProductApi
        ListProduct:
          Type: Api
          Properties:
            Path: /product
            Method: get
            RestApiId:
              Ref: ProductApi
Outputs:
  ApiURL:
    Description: API Gateway endpoint URL for Prod stage for Product function
    Value:
      Fn::Sub: https://${ProductApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product/