concurrent = 10 # Limits how many jobs can run concurrently, across all registered runners. A value of 10 means no more than 10 jobs can run concurrently.
check_interval = 0  # Defines the interval length, in seconds, between new jobs check. The default value is 3. If set to 0 or lower, the default value is used.

[session_server]
  session_timeout = 1800

[[runners]]
  name = "${RUNNER_NAME}"
  url = "${GITLAB_URL}/" # default url of the gitlab server
  token = "${RUNNER_AUTH_TOKEN}"  # token for repo or for the shared runner. Path:  button Register a group runner -> token
  executor = "custom"
  builds_dir = "/tmp/build"
  cache_dir = "/tmp/cache"
  [runners.custom]
    config_exec = "/usr/local/bin/fargate-linux-amd64"
    config_args = ["--config", "/etc/gitlab-runner/config_driver.toml", "custom", "config"]
    prepare_exec = "/usr/local/bin/fargate-linux-amd64"
    prepare_args = ["--config", "/etc/gitlab-runner/config_driver.toml", "custom", "prepare"]
    run_exec = "/usr/local/bin/fargate-linux-amd64"
    run_args = ["--config", "/etc/gitlab-runner/config_driver.toml", "custom", "run"]
    cleanup_exec = "/usr/local/bin/fargate-linux-amd64"
    cleanup_args = ["--config", "/etc/gitlab-runner/config_driver.toml", "custom", "cleanup"]
  [runners.cache]
    Type = "s3"
    Shared = true
    [runners.cache.s3]
    ServerAddress = "s3.amazonaws.com"
      BucketName = "gitlab-cache"
      BucketLocation = "us-east-1"