
spring:
  datasource:
    url: jdbc:h2:mem:dcbapp
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

redis:
  url: redis://127.0.0.1:6379 # for deployment you should override this value using env variable: export redis_url=<your-url>

server:
  port: 8081