LogLevel = "info"
LogFormat = "text"

[Fargate]
    cluster = "${FARGATE_CLUSTER}"
    region = "${FARGATE_REGION}"
    subnet = "${FARGATE_SUBNET}"
    securityGroup = "${FARGATE_SECURITY_GROUP}"
    TaskDefinition = "${FARGATE_TASK_DEFINITION}"
    EnablePublicIP = false #should be false because of Fargate

[TaskMetadata]
    Directory = "/tmp/"

[SSH]
    Username = "root"
    Port = 22